English:
  system_instruction: |-
    The following are multiple choice questions (with answers) about {subject}.
    You are an expert in question answering. Given a question and a set of choices, provide the correct answer. Answer exactly as '{"answer": "[label]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"answer": "'
  assistant_template: '{"answer": "{answer}"}'

Italian:
  system_instruction: |-
    Di seguito sono riportate domande a risposta multipla (con risposte) su {subject}.
    Sei un esperto nel rispondere alle domande. Data una domanda e una serie di opzioni, fornisci la risposta corretta. Rispondi esattamente come '{"risposta": "[etichetta]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"risposta": "'
  assistant_template: '{"risposta": "{answer}"}'

Friulian:
  system_instruction: |-
    Di seguit a son domandis a sielte multiple (cun rispuestis) su {subject}.
    Tu sês un esperts inte rispueste aes domandis. Date une domande e un insiemi di sieltis, dâ la rispueste corete. Rispuindi in mût esat come '{"rispueste": "[etichete]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"rispueste": "'
  assistant_template: '{"rispueste": "{answer}"}'

Venetian:
  system_instruction: |-
    Qua soto ghe xe domande a risposta (co risposte) su {subject}.
    Te si un esperto neła risposta ałe domande. Se ghe xe na domanda e un insieme de sielte, dà ła risposta giusta. Rispondi esattamente come '{"risposta": "[etichetta]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"risposta": "'
  assistant_template: '{"risposta": "{answer}"}'

Lombard:
  system_instruction: |-
    Di seguit sun dumandi a scernida multipla (cun rispost) sü {subject}.
    L’è un espert in de la risposta a la dumanda. Dat una dumanda e un insema de scernid, dà la rispòsta giüsta. Rispund en mod esatt cuma '{"rispòsta": "[etichetta]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"rispòsta": "'
  assistant_template: '{"rispòsta": "{answer}"}'

Sicilian:
  system_instruction: |-
    Di seguitu ci sunnu dumanni a scelta multipla (cû risposti) supra {subject}.
    Tu sì n'espertu nnâ risposta â dumanna. Data 'na dumanna e 'n 'nzèmi ri scelti, furnisci a risposta giusta. Rispunni esattamenti comu '{"risposta": "[etichetta]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"risposta": "'
  assistant_template: '{"risposta": "{answer}"}'

Ligurian:
  system_instruction: |-
    De sotta gh'é de domande à çernia multipla (con de respòste) in sce {subject}.
    Sei un esperto inta domanda de respòsta. Dæto unna domanda e un insemme de çernie, fornî a respòsta corretta. Responde esattamente comme '{"responsa": "[etichetta]"}'.
  user_template: |-
    {question}
    {choices}
  assistant_prefill: '{"responsa": "'
  assistant_template: '{"responsa": "{answer}"}'
